# Generated by Django 5.0.7 on 2024-10-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.URLField(),
        ),
    ]
