# Generated by Django 5.0.7 on 2024-10-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_thumbnail_alter_movie_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.FileField(upload_to=None, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(upload_to=None, verbose_name=''),
        ),
    ]
