# Generated by Django 5.0.7 on 2024-10-26 10:50

import movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_thumbnail_alter_movie_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='static/images/', validators=[movie.models.validate_image_format]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static/videos/', validators=[movie.models.validate_video_format]),
        ),
    ]
