# Generated by Django 5.0.7 on 2024-10-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_remove_movie_history_movie_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
