# Generated by Django 5.0.7 on 2024-10-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_user',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
